version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-rest-container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh /app/entrypoint.sh